services:
  hytale-server:
    build: .
    container_name: hytale-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    env_file: .env
    environment:
      - HYTALE_RAM=${HYTALE_RAM}
      - HYTALE_JAR=${HYTALE_JAR}
      - HYTALE_ASSETS=${HYTALE_ASSETS}
      - HYTALE_SERVER_SESSION_TOKEN=${HYTALE_SERVER_SESSION_TOKEN}
      - HYTALE_SERVER_IDENTITY_TOKEN=${HYTALE_SERVER_IDENTITY_TOKEN}
    ports:
      - "${HYTALE_PORT}:5520/udp"
    volumes:
      - ./data:/hytale
    networks:
      - hytale-net

networks:
  hytale-net:
    driver: bridge
